services:
  - type: web
    name: liberal-api-nif
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
